#zsh
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
zmodload zsh/nearcolor
alias sshpi='ssh w@192.168.1.25'
alias lf=lfrun
alias lsl='ls -latrh'
alias cpr='cp -r'
alias cpv='cp -v'
alias lsa='ls -a'
#zsh end

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
autoload -U compinit && compinit
zinit light zsh-users/zsh-autosuggestions
#zinit end

#pure start
fpath+=($HOME/.zsh/pure)
autoload -U promptinit; promptinit
PURE_PROMPT_SYMBOL="❯"
zstyle :prompt:pure:path color blue 
zstyle :prompt:pure:prompt:success color aeffff  
zstyle :prompt:pure:prompt:error color red
zstyle :prompt:pure:git:stash show yes

prompt pure
#pure end
